# Timezone mappings
timezones_dict = {
        'newzealand': [('auckland', 'akl', 'Pacific/Auckland', 'GMT+13'), 
                       ('wellington', 'wlg', 'Pacific/Auckland', 'GMT+13'), 
                       ('christchurch', 'chc', 'Pacific/Auckland', 'GMT+13'), 
                       ('hamilton', 'hlz', 'Pacific/Auckland', 'GMT+13')],
        'nz': [('auckland', 'akl', 'Pacific/Auckland', 'GMT+13'), 
               ('wellington', 'wlg', 'Pacific/Auckland', 'GMT+13'), 
               ('christchurch', 'chc', 'Pacific/Auckland', 'GMT+13'), 
               ('hamilton', 'hlz', 'Pacific/Auckland', 'GMT+13')],
        'australia': [('sydney', 'syd', 'Australia/Sydney', 'GMT+11'), 
                      ('melbourne', 'mel', 'Australia/Melbourne', 'GMT+11'), 
                      ('brisbane', 'bne', 'Australia/Brisbane', 'GMT+10'), 
                      ('perth', 'per', 'Australia/Perth', 'GMT+8'), 
                      ('adelaide', 'adl', 'Australia/Adelaide', 'GMT+10.5'), 
                      ('canberra', 'cbr', 'Australia/Sydney', 'GMT+11')],
        'au': [('sydney', 'syd', 'Australia/Sydney', 'GMT+11'), 
               ('melbourne', 'mel', 'Australia/Melbourne', 'GMT+11'), 
               ('brisbane', 'bne', 'Australia/Brisbane', 'GMT+10'), 
               ('perth', 'per', 'Australia/Perth', 'GMT+8'), 
               ('adelaide', 'adl', 'Australia/Adelaide', 'GMT+10.5'), 
               ('canberra', 'cbr', 'Australia/Sydney', 'GMT+11')],
        'bangladesh': [('dhaka', 'dac', 'Asia/Dhaka', 'GMT+6')],
        'bd': [('dhaka', 'dac', 'Asia/Dhaka', 'GMT+6')],
        'malaysia': [('kuala lumpur', 'kl', 'Asia/Kuala_Lumpur', 'GMT+8')],
        'my': [('kuala lumpur', 'kl', 'Asia/Kuala_Lumpur', 'GMT+8')],
        'mauritius': [('port louis', 'plu', 'Indian/Mauritius', 'GMT+4')],
        'mu': [('port louis', 'plu', 'Indian/Mauritius', 'GMT+4')],
        'canada': [('toronto', 'yyz', 'America/Toronto', 'GMT-5'), 
                   ('vancouver', 'yvr', 'America/Vancouver', 'GMT-8'), 
                   ('montreal', 'yul', 'America/Toronto', 'GMT-5'), 
                   ('calgary', 'yyc', 'America/Edmonton', 'GMT-7'), 
                   ('ottawa', 'yow', 'America/Toronto', 'GMT-5')],
        'ca': [('toronto', 'yyz', 'America/Toronto', 'GMT-5'), 
               ('vancouver', 'yvr', 'America/Vancouver', 'GMT-8'), 
               ('montreal', 'yul', 'America/Toronto', 'GMT-5'), 
               ('calgary', 'yyc', 'America/Edmonton', 'GMT-7'), 
               ('ottawa', 'yow', 'America/Toronto', 'GMT-5')],
        'unitedstates': [('new york', 'nyc', 'America/New_York', 'GMT-5'), 
                         ('los angeles', 'lax', 'America/Los_Angeles', 'GMT-8'), 
                         ('chicago', 'chi', 'America/Chicago', 'GMT-6'), 
                         ('houston', 'hou', 'America/Chicago', 'GMT-6'), 
                         ('phoenix', 'phx', 'America/Phoenix', 'GMT-7'), 
                         ('seattle', 'sea', 'America/Los_Angeles', 'GMT-8'), 
                         ('miami', 'mia', 'America/New_York', 'GMT-5'),
                         ('atlanta', 'atl', 'America/New_York', 'GMT-5'),
                         ('dallas', 'dfw', 'America/Chicago', 'GMT-6')],
        'us': [('new york', 'nyc', 'America/New_York', 'GMT-5'), 
               ('los angeles', 'lax', 'America/Los_Angeles', 'GMT-8'), 
               ('chicago', 'chi', 'America/Chicago', 'GMT-6'), 
               ('houston', 'hou', 'America/Chicago', 'GMT-6'), 
               ('phoenix', 'phx', 'America/Phoenix', 'GMT-7'), 
               ('seattle', 'sea', 'America/Los_Angeles', 'GMT-8'), 
               ('miami', 'mia', 'America/New_York', 'GMT-5'),
               ('atlanta', 'atl', 'America/New_York', 'GMT-5'),
               ('dallas', 'dfw', 'America/Chicago', 'GMT-6')],
        'england': [('london', 'lon', 'Europe/London', 'GMT+0'), 
                    ('manchester', 'man', 'Europe/London', 'GMT+0'), 
                    ('birmingham', 'bhx', 'Europe/London', 'GMT+0'), 
                    ('liverpool', 'lpl', 'Europe/London', 'GMT+0')],
        'uk': [('london', 'lon', 'Europe/London', 'GMT+0'), 
               ('manchester', 'man', 'Europe/London', 'GMT+0'), 
               ('birmingham', 'bhx', 'Europe/London', 'GMT+0'), 
               ('liverpool', 'lpl', 'Europe/London', 'GMT+0')],
        'germany': [('berlin', 'ber', 'Europe/Berlin', 'GMT+1'), 
                    ('munich', 'muc', 'Europe/Berlin', 'GMT+1'), 
                    ('frankfurt', 'fra', 'Europe/Berlin', 'GMT+1')],
        'ger': [('berlin', 'ber', 'Europe/Berlin', 'GMT+1'), 
                    ('munich', 'muc', 'Europe/Berlin', 'GMT+1'), 
                    ('frankfurt', 'fra', 'Europe/Berlin', 'GMT+1')],
        'france': [('paris', 'par', 'Europe/Paris', 'GMT+1'), 
                   ('lyon', 'lys', 'Europe/Paris', 'GMT+1'), 
                   ('marseille', 'mrs', 'Europe/Paris', 'GMT+1')],
        'fr': [('paris', 'par', 'Europe/Paris', 'GMT+1'), 
                   ('lyon', 'lys', 'Europe/Paris', 'GMT+1'), 
                   ('marseille', 'mrs', 'Europe/Paris', 'GMT+1')],
        'italy': [('rome', 'rom', 'Europe/Rome', 'GMT+1'), 
                  ('milan', 'mil', 'Europe/Rome', 'GMT+1'), 
                  ('naples', 'nap', 'Europe/Rome', 'GMT+1')],
        'it': [('rome', 'rom', 'Europe/Rome', 'GMT+1'), 
                  ('milan', 'mil', 'Europe/Rome', 'GMT+1'), 
                  ('naples', 'nap', 'Europe/Rome', 'GMT+1')],
        'netherlands': [('amsterdam', 'ams', 'Europe/Amsterdam', 'GMT+1'), 
                        ('rotterdam', 'rtm', 'Europe/Amsterdam', 'GMT+1')],
        'nl': [('amsterdam', 'ams', 'Europe/Amsterdam', 'GMT+1'), 
                        ('rotterdam', 'rtm', 'Europe/Amsterdam', 'GMT+1')],
        'denmark': [('copenhagen', 'cph', 'Europe/Copenhagen', 'GMT+1')],
        'dk': [('copenhagen', 'cph', 'Europe/Copenhagen', 'GMT+1')],
        'finland': [('helsinki', 'hel', 'Europe/Helsinki', 'GMT+2')],
        'fi': [('helsinki', 'hel', 'Europe/Helsinki', 'GMT+2')],
        'switzerland': [('zurich', 'zrh', 'Europe/Zurich', 'GMT+1'), 
                        ('geneva', 'gva', 'Europe/Zurich', 'GMT+1')],
        'ch': [('zurich', 'zrh', 'Europe/Zurich', 'GMT+1'), 
                        ('geneva', 'gva', 'Europe/Zurich', 'GMT+1')],
        'luxembourg': [('luxembourg', 'lxm', 'Europe/Luxembourg', 'GMT+1')],
        'lu': [('luxembourg', 'lxm', 'Europe/Luxembourg', 'GMT+1')],
        'philippines': [('manila', 'mnl', 'Asia/Manila', 'GMT+8'), 
                ('davao', 'dav', 'Asia/Manila', 'GMT+8')],
        'ph': [('manila', 'mnl', 'Asia/Manila', 'GMT+8'), 
                ('davao', 'dav', 'Asia/Manila', 'GMT+8')],
        'singapore': [('singapore', 'sin', 'Asia/Singapore', 'GMT+8')],
        'sg': [('singapore', 'sin', 'Asia/Singapore', 'GMT+8')],
        'japan': [('tokyo', 'tk', 'Asia/Tokyo', 'GMT+9')],
        'jp': [('tokyo', 'tk', 'Asia/Tokyo', 'GMT+9')]
        
    }

USER_LOCATION_MAPPING = {
    "340485392434200576": ("list", "Hamilton, NZ"),
    "744440440786255994": ("Bronoy", "Dhaka, BD"),
    "697901157472796826": ("Bush", "Dhaka, BD"),
    "439530718352375827": ("curlysandwich", "New York, US"),
    "626150404333371422": ("gl1vch", "Toronto, CA"),
    "313373154812755969": ("Ibrahim", "Kuala Lumpur, MY"),
    "701305433633194018": ("ItznotHawk", "Melbourne, AU"),
    "709061499066515476": ("mehnaz", "New York, US"),
    "719836306569429064": ("Moose", "Dhaka, BD"),
    "665657749207777351": ("Nay", "Toronto, CA"),
    "428113253726683137": ("Nowfel", "Toronto, CA"),
    "544753860858871831": ("ORANGMAN", "Auckland, NZ"),
    "392683322805059587": ("Relic", "Dhaka, BD"),
    "422394995266551808": ("Shamo_99", "Luxembourg, LU"),
    "692430092592218123": ("Skibby", "Kuala Lumpur, MY"),
    "368379417208029185": ("strangyyy", "Dhaka, BD"),
    "488021414759366668": ("tooshiewooshie", "Dhaka, BD"),
    "426522676581105676": ("Verse", "Dhaka, BD"),
    "487064547832627200": ("Alex", "Port Louis, MU"),
    "960839376563236894": ("Yashfi", "Kuala Lumpur, MY"),
    "219797015066968064": ("Zer0", "Toronto, CA"),
    "425981881138413568": ("ZiWei", "Kuala Lumpur, MY"),
    "1255921404185018462": ("rinochaino", "Dhaka, BD"),
}



# dictionary to store user ID, username, and city mappings
# redacted for privacy, obviously 
USER_TIMEZONE_MAPPING = {
    340485392434200576: ("list", "hlz"),
    744440440786255994: ("Bronoy", "dac"),
    697901157472796826: ("Bush", "dac"),
    439530718352375827: ("curlysandwich", "nyc"),
    626150404333371422: ("gl1vch", "yyz"),
    313373154812755969: ("Ibrahim", "kl"),
    701305433633194018: ("ItznotHawk", "mel"),
    709061499066515476: ("mehnaz", "nyc"),
    719836306569429064: ("Moose", "dac"),
    665657749207777351: ("Nay", "yyz"),
    428113253726683137: ("Nowfel", "yyz"),
    544753860858871831: ("ORANGMAN", "akl"),
    392683322805059587: ("Relic", "dac"),
    422394995266551808: ("Shamo_99", "lxm"),
    692430092592218123: ("Skibby", "kl"),
    368379417208029185: ("strangyyy", "dac"),
    488021414759366668: ("tooshiewooshie", "dac"),
    426522676581105676: ("Verse", "dac"),
    487064547832627200: ("Alex", "plu"),
    960839376563236894: ("Yashfi", "kl"),
    219797015066968064: ("Zer0", "yyz"),
    425981881138413568: ("ZiWei", "kl"),
    1255921404185018462: ("rinochaino", "dac"),
}

# Mapping currency codes to (singular name, plural name) where anything but 1 returns plural (or so i hope)
# Required for both conv and clist
CURRENCY_NAMES = {
    'USD': ('United States Dollar', 'United States Dollars'),
    'NZD': ('New Zealand Dollar', 'New Zealand Dollars'),
    'CAD': ('Canadian Dollar', 'Canadian Dollars'),
    'BDT': ('Bangladeshi Taka', 'Bangladeshi Taka'),
    'MYR': ('Malaysian Ringgit', 'Malaysian Ringgit'),
    'MUR': ('Mauritian Rupee', 'Mauritian Rupees'),
    'EUR': ('Euro', 'Euros'),
    'EGP': ('Egyptian Pound', 'Egyptian Pounds'),
    'SAR': ('Saudi Riyal', 'Saudi Riyals'),
    'TRY': ('Turkish Lira', 'Turkish Lira'),
    'GBP': ('British Pound', 'British Pounds'),
    'AUD': ('Australian Dollar', 'Australian Dollars'),
    'PHP': ('Philippine Peso', 'Philippine Pesos'),
    'CNY': ('Chinese Yuan', 'Chinese Yuan'),
    'SGD': ('Singapore Dollar', 'Singapore Dollars'),
    'JPY': ('Japanese Yen', 'Japanese Yen')
}

# Abbreviation mapping for countries used in 'tlist' in on_message
COUNTRY_ABBREVIATIONS = {
    'newzealand': 'NZ',
    'australia': 'AU',
    'bangladesh': 'BD',
    'malaysia': 'MY',
    'mauritius': 'MU',
    'canada': 'CA',
    'unitedstates': 'US',
    'england': 'UK',
    'germany': 'GER',
    'france': 'FR',
    'italy': 'IT',
    'denmark': 'DK',
    'netherlands': 'NL',
    'finland': 'FI',
    'switzerland': 'CH',
    'luxembourg' : 'LU',
    'singapore' : 'SG',
    'philippines' : 'PH',
    'japan' : 'JP'
}

# List of supported currencies
SUPPORTED_CURRENCIES = ['USD', 'NZD', 'CAD', 'BDT', 'MYR', 'MUR', 'EUR', 'EGP', 'SAR', 'TRY', 'GBP', 'AUD', 'PHP', 'CNY', 'SGD', 'JPY'] 


